"""Sample categories and a coherent example PC build used by the in-memory repositories.

The products form one compatible AM5 gaming build (CPU + cooler + motherboard +
RAM + GPU + storage + PSU + case) plus a monitor and peripherals — one item per
category.
"""

from decimal import Decimal

from app.models import Category, Product

SEED_CATEGORIES: list[Category] = [
    Category(slug="processors", name="Processors", description="CPUs.", sort_order=1),
    Category(slug="cpu-coolers", name="CPU Coolers", description="Air and liquid CPU cooling.", sort_order=2),
    Category(slug="motherboards", name="Motherboards", description="Mainboards.", sort_order=3),
    Category(slug="memory", name="Memory (RAM)", description="System memory.", sort_order=4),
    Category(slug="graphics-cards", name="Graphics Cards", description="GPUs for gaming and compute.", sort_order=5),
    Category(slug="storage", name="Storage", description="SSDs and hard drives.", sort_order=6),
    Category(slug="power-supplies", name="Power Supplies", description="PSUs.", sort_order=7),
    Category(slug="cases", name="Cases", description="PC chassis.", sort_order=8),
    Category(slug="monitors", name="Monitors", description="Displays.", sort_order=9),
    Category(slug="keyboards", name="Keyboards", description="Keyboards.", sort_order=10),
    Category(slug="mice", name="Mice", description="Mice.", sort_order=11),
    Category(slug="headsets", name="Headsets", description="Headsets.", sort_order=12),
]

SEED_PRODUCTS: list[Product] = [
    Product(
        id="cpu-ryzen-7800x3d",
        name="Ryzen 7 7800X3D",
        brand="AMD",
        category="processors",
        price=Decimal("349.00"),
        stock=20,
        description="8-core gaming CPU with 3D V-Cache.",
        image_key="products/cpu-ryzen-7800x3d/main.webp",
        specs={"cores": "8", "threads": "16", "socket": "AM5", "tdp": "120W"},
    ),
    Product(
        id="cooler-noctua-nh-d15",
        name="Noctua NH-D15 chromax.black",
        brand="Noctua",
        category="cpu-coolers",
        price=Decimal("119.95"),
        stock=15,
        description="Dual-tower air cooler.",
        image_key="products/cooler-noctua-nh-d15/main.webp",
        specs={"type": "Air", "height": "165mm", "sockets": "AM5 / LGA1700", "fans": "2x 140mm"},
    ),
    Product(
        id="mobo-asus-b650e-f",
        name="ROG STRIX B650E-F Gaming WiFi",
        brand="ASUS",
        category="motherboards",
        price=Decimal("289.99"),
        stock=9,
        description="AM5 ATX motherboard.",
        image_key="products/mobo-asus-b650e-f/main.webp",
        specs={"socket": "AM5", "chipset": "B650E", "form_factor": "ATX", "memory": "DDR5", "wifi": "Wi-Fi 6E"},
    ),
    Product(
        id="ram-gskill-z5-32gb",
        name="Trident Z5 Neo 32GB DDR5-6000 CL30",
        brand="G.Skill",
        category="memory",
        price=Decimal("119.99"),
        stock=30,
        description="32GB (2x16GB) DDR5 kit tuned for AM5.",
        image_key="products/ram-gskill-z5-32gb/main.webp",
        specs={"capacity": "32GB (2x16GB)", "type": "DDR5", "speed": "6000 MT/s", "cas": "CL30"},
    ),
    Product(
        id="gpu-rtx-4070",
        name="GeForce RTX 4070 Ti SUPER",
        brand="NVIDIA",
        category="graphics-cards",
        price=Decimal("799.00"),
        stock=7,
        description="High-end 1440p / entry 4K gaming GPU.",
        image_key="products/gpu-rtx-4070/main.webp",
        specs={"vram": "16GB GDDR6X", "tdp": "285W", "ports": "3x DP, 1x HDMI"},
    ),
    Product(
        id="ssd-samsung-990pro-2tb",
        name="990 PRO 2TB NVMe SSD",
        brand="Samsung",
        category="storage",
        price=Decimal("169.99"),
        stock=25,
        description="PCIe 4.0 NVMe solid-state drive.",
        image_key="products/ssd-samsung-990pro-2tb/main.webp",
        specs={"capacity": "2TB", "interface": "PCIe 4.0 NVMe", "form_factor": "M.2 2280", "read": "7450 MB/s"},
    ),
    Product(
        id="psu-corsair-rm850e",
        name="RM850e 850W 80+ Gold",
        brand="Corsair",
        category="power-supplies",
        price=Decimal("129.99"),
        stock=18,
        description="Fully modular ATX power supply.",
        image_key="products/psu-corsair-rm850e/main.webp",
        specs={"wattage": "850W", "rating": "80+ Gold", "modular": "Full", "form_factor": "ATX"},
    ),
    Product(
        id="case-lian-li-216",
        name="Lancool 216",
        brand="Lian Li",
        category="cases",
        price=Decimal("109.99"),
        stock=0,
        description="Airflow ATX mid-tower.",
        image_key="products/case-lian-li-216/main.webp",
        specs={"form_factor": "Mid Tower", "supports": "ATX / mATX / ITX", "gpu_clearance": "392mm", "included_fans": "3"},
    ),
    Product(
        id="mon-odyssey-g7",
        name="Odyssey G7 32\"",
        brand="Samsung",
        category="monitors",
        price=Decimal("649.00"),
        stock=5,
        description="32-inch 1440p 240Hz curved gaming monitor.",
        image_key="products/mon-odyssey-g7/main.webp",
        specs={"size": "32\"", "resolution": "2560x1440", "refresh": "240Hz", "panel": "VA"},
    ),
    Product(
        id="kbd-mx-keys",
        name="MX Keys S",
        brand="Logitech",
        category="keyboards",
        price=Decimal("109.00"),
        stock=40,
        description="Wireless low-profile productivity keyboard.",
        image_key="products/kbd-mx-keys/main.webp",
        specs={"layout": "Full-size", "connectivity": "Bluetooth / Logi Bolt", "backlight": "Yes"},
    ),
    Product(
        id="mouse-mx-master-3s",
        name="MX Master 3S",
        brand="Logitech",
        category="mice",
        price=Decimal("99.99"),
        stock=35,
        description="Wireless productivity mouse.",
        image_key="products/mouse-mx-master-3s/main.webp",
        specs={"dpi": "8000", "connectivity": "Bluetooth / Logi Bolt", "buttons": "7"},
    ),
    Product(
        id="headset-arctis-nova-7",
        name="Arctis Nova 7 Wireless",
        brand="SteelSeries",
        category="headsets",
        price=Decimal("149.99"),
        stock=12,
        description="Wireless gaming headset.",
        image_key=None,
        specs={"connectivity": "2.4GHz Wireless / Bluetooth", "drivers": "40mm", "mic": "Retractable"},
    ),
]
