"""Sample categories and products used by the in-memory repositories.

The catalog is being filled out category by category. Processors lists the full
AMD Ryzen 9000 and Intel Core Ultra 200S lineups; other categories currently hold
a single representative item each.
"""

from decimal import Decimal

from app.models import Category, Product

SEED_CATEGORIES: list[Category] = [
    Category(slug="processors", name="Processors", description="CPUs.", sort_order=1),
    Category(slug="cpu-coolers", name="CPU Coolers", description="Air and liquid CPU cooling.", sort_order=2),
    Category(slug="motherboards", name="Motherboards", description="Mainboards.", sort_order=3),
    Category(slug="memory", name="Memory (RAM)", description="System memory.", sort_order=4),
    Category(slug="graphics-cards", name="Graphics Cards", description="GPUs for gaming and compute.", sort_order=5),
    Category(slug="storage", name="Storage", description="SSDs and hard drives.", sort_order=6),
    Category(slug="power-supplies", name="Power Supplies", description="PSUs.", sort_order=7),
    Category(slug="cases", name="Cases", description="PC chassis.", sort_order=8),
    Category(slug="monitors", name="Monitors", description="Displays.", sort_order=9),
    Category(slug="keyboards", name="Keyboards", description="Keyboards.", sort_order=10),
    Category(slug="mice", name="Mice", description="Mice.", sort_order=11),
    Category(slug="headsets", name="Headsets", description="Headsets.", sort_order=12),
]

SEED_PRODUCTS: list[Product] = [
    # --- Processors: AMD Ryzen 9000 (Zen 5, AM5) ---
    Product(
        id="cpu-ryzen-9600x",
        name="Ryzen 5 9600X",
        brand="AMD",
        category="processors",
        price=Decimal("279.00"),
        stock=30,
        description="Entry Zen 5 6-core for efficient mainstream builds.",
        image_key="cpus/amd.jpg",
        specs={"cores": "6", "threads": "12", "socket": "AM5", "boost_clock": "5.4 GHz", "cache": "32MB L3", "tdp": "65W"},
    ),
    Product(
        id="cpu-ryzen-9700x",
        name="Ryzen 7 9700X",
        brand="AMD",
        category="processors",
        price=Decimal("359.00"),
        stock=25,
        description="8-core Zen 5 sweet spot for gaming and productivity.",
        image_key="cpus/amd.jpg",
        specs={"cores": "8", "threads": "16", "socket": "AM5", "boost_clock": "5.5 GHz", "cache": "32MB L3", "tdp": "65W"},
    ),
    Product(
        id="cpu-ryzen-9900x",
        name="Ryzen 9 9900X",
        brand="AMD",
        category="processors",
        price=Decimal("499.00"),
        stock=18,
        description="12-core Zen 5 for heavy multitasking and content creation.",
        image_key="cpus/amd.jpg",
        specs={"cores": "12", "threads": "24", "socket": "AM5", "boost_clock": "5.6 GHz", "cache": "64MB L3", "tdp": "120W"},
    ),
    Product(
        id="cpu-ryzen-9950x",
        name="Ryzen 9 9950X",
        brand="AMD",
        category="processors",
        price=Decimal("649.00"),
        stock=12,
        description="Flagship 16-core Zen 5 for serious productivity.",
        image_key="cpus/amd.jpg",
        specs={"cores": "16", "threads": "32", "socket": "AM5", "boost_clock": "5.7 GHz", "cache": "64MB L3", "tdp": "170W"},
    ),
    Product(
        id="cpu-ryzen-9800x3d",
        name="Ryzen 7 9800X3D",
        brand="AMD",
        category="processors",
        price=Decimal("479.00"),
        stock=0,
        description="8-core with 2nd-gen 3D V-Cache — top-tier gaming.",
        image_key="cpus/amd.jpg",
        specs={"cores": "8", "threads": "16", "socket": "AM5", "boost_clock": "5.2 GHz", "cache": "96MB (3D V-Cache)", "tdp": "120W"},
    ),
    Product(
        id="cpu-ryzen-9850x3d",
        name="Ryzen 7 9850X3D",
        brand="AMD",
        category="processors",
        price=Decimal("499.00"),
        stock=8,
        description="Refined 8-core 3D V-Cache with higher clocks than the 9800X3D.",
        image_key="cpus/amd.jpg",
        specs={"cores": "8", "threads": "16", "socket": "AM5", "boost_clock": "5.6 GHz", "cache": "96MB (3D V-Cache)", "tdp": "120W"},
    ),
    Product(
        id="cpu-ryzen-9900x3d",
        name="Ryzen 9 9900X3D",
        brand="AMD",
        category="processors",
        price=Decimal("599.00"),
        stock=10,
        description="12-core 3D V-Cache balancing gaming and creation.",
        image_key="cpus/amd.jpg",
        specs={"cores": "12", "threads": "24", "socket": "AM5", "boost_clock": "5.5 GHz", "cache": "128MB (3D V-Cache)", "tdp": "120W"},
    ),
    Product(
        id="cpu-ryzen-9950x3d",
        name="Ryzen 9 9950X3D",
        brand="AMD",
        category="processors",
        price=Decimal("699.00"),
        stock=6,
        description="16-core 3D V-Cache — elite gaming and productivity.",
        image_key="cpus/amd.jpg",
        specs={"cores": "16", "threads": "32", "socket": "AM5", "boost_clock": "5.7 GHz", "cache": "128MB (3D V-Cache)", "tdp": "170W"},
    ),
    Product(
        id="cpu-ryzen-9950x3d2",
        name="Ryzen 9 9950X3D2 Dual Edition",
        brand="AMD",
        category="processors",
        price=Decimal("799.00"),
        stock=3,
        description="Dual 3D V-Cache edition (192MB) for creators and developers.",
        image_key="cpus/amd.jpg",
        specs={"cores": "16", "threads": "32", "socket": "AM5", "boost_clock": "5.6 GHz", "cache": "192MB (3D V-Cache)", "tdp": "200W"},
    ),
    # --- Processors: Intel Core Ultra 200S (Arrow Lake, LGA1851) ---
    Product(
        id="cpu-intel-285k",
        name="Core Ultra 9 285K",
        brand="Intel",
        category="processors",
        price=Decimal("589.00"),
        stock=14,
        description="Flagship 24-core Arrow Lake with on-package NPU.",
        image_key="cpus/intel.jpg",
        specs={"cores": "24 (8P + 16E)", "threads": "24", "socket": "LGA1851", "boost_clock": "5.7 GHz", "cache": "36MB L3", "tdp": "125W (250W max)"},
    ),
    Product(
        id="cpu-intel-265k",
        name="Core Ultra 7 265K",
        brand="Intel",
        category="processors",
        price=Decimal("394.00"),
        stock=20,
        description="20-core Arrow Lake for high-end gaming and multitasking.",
        image_key="cpus/intel.jpg",
        specs={"cores": "20 (8P + 12E)", "threads": "20", "socket": "LGA1851", "boost_clock": "5.5 GHz", "cache": "30MB L3", "tdp": "125W (250W max)"},
    ),
    Product(
        id="cpu-intel-265kf",
        name="Core Ultra 7 265KF",
        brand="Intel",
        category="processors",
        price=Decimal("379.00"),
        stock=16,
        description="20-core Arrow Lake with no integrated graphics — pair with a discrete GPU.",
        image_key="cpus/intel.jpg",
        specs={"cores": "20 (8P + 12E)", "threads": "20", "socket": "LGA1851", "boost_clock": "5.5 GHz", "cache": "30MB L3", "tdp": "125W (250W max)"},
    ),
    Product(
        id="cpu-intel-245k",
        name="Core Ultra 5 245K",
        brand="Intel",
        category="processors",
        price=Decimal("309.00"),
        stock=28,
        description="14-core Arrow Lake for mainstream high-performance builds.",
        image_key="cpus/intel.jpg",
        specs={"cores": "14 (6P + 8E)", "threads": "14", "socket": "LGA1851", "boost_clock": "5.2 GHz", "cache": "24MB L3", "tdp": "125W (159W max)"},
    ),
    Product(
        id="cpu-intel-245kf",
        name="Core Ultra 5 245KF",
        brand="Intel",
        category="processors",
        price=Decimal("294.00"),
        stock=22,
        description="14-core Arrow Lake with no integrated graphics.",
        image_key="cpus/intel.jpg",
        specs={"cores": "14 (6P + 8E)", "threads": "14", "socket": "LGA1851", "boost_clock": "5.2 GHz", "cache": "24MB L3", "tdp": "125W (159W max)"},
    ),
    # --- CPU Coolers: Noctua air ---
    Product(
        id="cooler-noctua-nh-d15-g2",
        name="Noctua NH-D15 G2",
        brand="Noctua",
        category="cpu-coolers",
        price=Decimal("149.95"),
        stock=12,
        description="Flagship dual-tower air cooler that rivals many 240mm AIOs.",
        image_key="coolers/cooler-noctua-nh-d15-g2.jpg",
        specs={"type": "Air", "height": "168mm", "heatpipes": "8", "fans": "2x 140mm", "sockets": "AM5 / LGA1851 / LGA1700"},
    ),
    Product(
        id="cooler-noctua-nh-u12a",
        name="Noctua NH-U12A",
        brand="Noctua",
        category="cpu-coolers",
        price=Decimal("129.95"),
        stock=18,
        description="Premium 120mm single-tower with great RAM and PCIe clearance.",
        image_key="coolers/cooler-noctua-nh-u12a.jpg",
        specs={"type": "Air", "height": "158mm", "heatpipes": "7", "fans": "2x 120mm", "sockets": "AM5 / LGA1851 / LGA1700"},
    ),
    Product(
        id="cooler-noctua-nh-l12s",
        name="Noctua NH-L12S",
        brand="Noctua",
        category="cpu-coolers",
        price=Decimal("69.95"),
        stock=20,
        description="Low-profile cooler for small-form-factor builds.",
        image_key="coolers/cooler-noctua-nh-l12s.jpg",
        specs={"type": "Air (low-profile)", "height": "70mm", "heatpipes": "4", "fans": "1x 120mm", "sockets": "AM5 / LGA1851 / LGA1700"},
    ),
    # --- CPU Coolers: Gigabyte AORUS WATERFORCE X (AIO) ---
    Product(
        id="cooler-aorus-waterforce-x-360",
        name="AORUS WATERFORCE X 360",
        brand="Gigabyte",
        category="cpu-coolers",
        price=Decimal("269.99"),
        stock=8,
        description="360mm AIO liquid cooler with a rotatable circular LCD.",
        image_key="coolers/cooler-aorus-waterforce-x-360.jpg",
        specs={"type": "Liquid (AIO)", "radiator": "360mm", "fans": "3x 120mm ARGB", "display": "Circular LCD", "sockets": "AM5 / LGA1851 / LGA1700"},
    ),
    Product(
        id="cooler-aorus-waterforce-x-280",
        name="AORUS WATERFORCE X 280",
        brand="Gigabyte",
        category="cpu-coolers",
        price=Decimal("239.99"),
        stock=6,
        description="280mm AIO liquid cooler with a rotatable circular LCD.",
        image_key="coolers/cooler-aorus-waterforce-x-280.jpg",
        specs={"type": "Liquid (AIO)", "radiator": "280mm", "fans": "2x 140mm ARGB", "display": "Circular LCD", "sockets": "AM5 / LGA1851 / LGA1700"},
    ),
    Product(
        id="cooler-aorus-waterforce-x-240",
        name="AORUS WATERFORCE X 240",
        brand="Gigabyte",
        category="cpu-coolers",
        price=Decimal("199.99"),
        stock=10,
        description="240mm AIO liquid cooler with a rotatable circular LCD.",
        image_key="coolers/cooler-aorus-waterforce-x-240.jpg",
        specs={"type": "Liquid (AIO)", "radiator": "240mm", "fans": "2x 120mm ARGB", "display": "Circular LCD", "sockets": "AM5 / LGA1851 / LGA1700"},
    ),
    # --- Motherboards: AM5 (Ryzen 9000) ---
    Product(
        id="mobo-gigabyte-b650-elite-ax",
        name="B650 AORUS ELITE AX",
        brand="Gigabyte",
        category="motherboards",
        price=Decimal("199.99"),
        stock=15,
        description="Budget AM5 ATX board with DDR5 and Wi-Fi 6E.",
        image_key="motherboards/mobo-gigabyte-b650-elite-ax.jpg",
        specs={"socket": "AM5", "chipset": "B650", "form_factor": "ATX", "memory": "DDR5", "pcie": "PCIe 4.0", "wifi": "Wi-Fi 6E"},
    ),
    Product(
        id="mobo-gigabyte-x870-elite-wifi7",
        name="X870 AORUS ELITE WIFI7",
        brand="Gigabyte",
        category="motherboards",
        price=Decimal("289.99"),
        stock=12,
        description="Mid-range AM5 board with PCIe 5.0, USB4 and Wi-Fi 7.",
        image_key="motherboards/mobo-gigabyte-x870-elite-wifi7.jpg",
        specs={"socket": "AM5", "chipset": "X870", "form_factor": "ATX", "memory": "DDR5", "pcie": "PCIe 5.0", "wifi": "Wi-Fi 7"},
    ),
    Product(
        id="mobo-gigabyte-x870e-master",
        name="X870E AORUS MASTER",
        brand="Gigabyte",
        category="motherboards",
        price=Decimal("499.99"),
        stock=6,
        description="High-end AM5 board: 16+2+2 VRM, 4x M.2, dual USB4, 5GbE, Wi-Fi 7.",
        image_key="motherboards/mobo-gigabyte-x870e-master.jpg",
        specs={"socket": "AM5", "chipset": "X870E", "form_factor": "ATX", "memory": "DDR5 (up to 8600)", "pcie": "PCIe 5.0", "wifi": "Wi-Fi 7"},
    ),
    # --- Motherboards: Intel LGA1851 (Core Ultra 200S) ---
    Product(
        id="mobo-gigabyte-b860-elite-wifi7",
        name="B860 AORUS ELITE WIFI7",
        brand="Gigabyte",
        category="motherboards",
        price=Decimal("219.99"),
        stock=14,
        description="Budget LGA1851 board for Core Ultra 200S with Wi-Fi 7.",
        image_key="motherboards/mobo-gigabyte-b860-elite-wifi7.jpg",
        specs={"socket": "LGA1851", "chipset": "B860", "form_factor": "ATX", "memory": "DDR5", "pcie": "PCIe 5.0", "wifi": "Wi-Fi 7"},
    ),
    Product(
        id="mobo-gigabyte-z890-elite-wifi7",
        name="Z890 AORUS ELITE WIFI7",
        brand="Gigabyte",
        category="motherboards",
        price=Decimal("319.99"),
        stock=10,
        description="Mid-range Z890 board with PCIe 5.0, USB4 and Wi-Fi 7.",
        image_key="motherboards/mobo-gigabyte-z890-elite-wifi7.jpg",
        specs={"socket": "LGA1851", "chipset": "Z890", "form_factor": "ATX", "memory": "DDR5", "pcie": "PCIe 5.0", "wifi": "Wi-Fi 7"},
    ),
    Product(
        id="mobo-gigabyte-z890-master",
        name="Z890 AORUS MASTER",
        brand="Gigabyte",
        category="motherboards",
        price=Decimal("499.99"),
        stock=5,
        description="High-end Z890 board: high-phase VRM, dual USB4, 5GbE, Wi-Fi 7.",
        image_key="motherboards/mobo-gigabyte-z890-master.jpg",
        specs={"socket": "LGA1851", "chipset": "Z890", "form_factor": "ATX", "memory": "DDR5", "pcie": "PCIe 5.0", "wifi": "Wi-Fi 7"},
    ),
    # --- Memory: DDR5 (works on both AM5 and LGA1851) ---
    Product(
        id="ram-gskill-ddr5-5600-32gb",
        name="G.Skill Ripjaws S5 32GB DDR5-5600 CL36",
        brand="G.Skill",
        category="memory",
        price=Decimal("94.99"),
        stock=40,
        description="Entry 32GB (2x16GB) DDR5-5600 kit.",
        image_key="memory/ram-gskill-ddr5-5600-32gb.jpg",
        specs={"capacity": "32GB (2x16GB)", "type": "DDR5", "speed": "5600 MT/s", "cas": "CL36"},
    ),
    Product(
        id="ram-gskill-ddr5-6000-32gb",
        name="G.Skill Trident Z5 Neo RGB 32GB DDR5-6000 CL30",
        brand="G.Skill",
        category="memory",
        price=Decimal("119.99"),
        stock=30,
        description="Sweet-spot 32GB (2x16GB) DDR5-6000 CL30 kit.",
        image_key="memory/ram-gskill-ddr5-6000-32gb.jpg",
        specs={"capacity": "32GB (2x16GB)", "type": "DDR5", "speed": "6000 MT/s", "cas": "CL30"},
    ),
    Product(
        id="ram-gskill-ddr5-6400-32gb",
        name="G.Skill Trident Z5 RGB 32GB DDR5-6400 CL32",
        brand="G.Skill",
        category="memory",
        price=Decimal("139.99"),
        stock=20,
        description="High-speed 32GB (2x16GB) DDR5-6400 CL32 kit.",
        image_key="memory/ram-gskill-ddr5-6400-32gb.jpg",
        specs={"capacity": "32GB (2x16GB)", "type": "DDR5", "speed": "6400 MT/s", "cas": "CL32"},
    ),
    # --- Graphics Cards: Gigabyte RTX 50 series (non-AORUS) ---
    Product(
        id="gpu-gigabyte-rtx-5060",
        name="GeForce RTX 5060 WINDFORCE OC 8G",
        brand="Gigabyte",
        category="graphics-cards",
        price=Decimal("299.00"),
        stock=20,
        description="Entry 1080p Blackwell GPU.",
        image_key="graphics-cards/gpu-gigabyte-rtx-5060.jpg",
        specs={"vram": "8GB GDDR7", "bus": "128-bit", "tdp": "145W", "ports": "3x DP 2.1b, 1x HDMI 2.1"},
    ),
    Product(
        id="gpu-gigabyte-rtx-5060-ti",
        name="GeForce RTX 5060 Ti WINDFORCE OC 16G",
        brand="Gigabyte",
        category="graphics-cards",
        price=Decimal("429.00"),
        stock=15,
        description="Strong 1080p / entry 1440p GPU with 16GB.",
        image_key="graphics-cards/gpu-gigabyte-rtx-5060-ti.jpg",
        specs={"vram": "16GB GDDR7", "bus": "128-bit", "tdp": "180W", "ports": "3x DP 2.1b, 1x HDMI 2.1"},
    ),
    Product(
        id="gpu-gigabyte-rtx-5070",
        name="GeForce RTX 5070 WINDFORCE OC 12G",
        brand="Gigabyte",
        category="graphics-cards",
        price=Decimal("549.00"),
        stock=12,
        description="1440p high-refresh gaming GPU.",
        image_key="graphics-cards/gpu-gigabyte-rtx-5070.jpg",
        specs={"vram": "12GB GDDR7", "bus": "192-bit", "tdp": "250W", "ports": "3x DP 2.1b, 1x HDMI 2.1"},
    ),
    Product(
        id="gpu-gigabyte-rtx-5070-ti",
        name="GeForce RTX 5070 Ti GAMING OC 16G",
        brand="Gigabyte",
        category="graphics-cards",
        price=Decimal("749.00"),
        stock=8,
        description="High-end 1440p / entry 4K GPU with 16GB.",
        image_key="graphics-cards/gpu-gigabyte-rtx-5070-ti.jpg",
        specs={"vram": "16GB GDDR7", "bus": "256-bit", "tdp": "300W", "ports": "3x DP 2.1b, 1x HDMI 2.1"},
    ),
    Product(
        id="gpu-gigabyte-rtx-5080",
        name="GeForce RTX 5080 GAMING OC 16G",
        brand="Gigabyte",
        category="graphics-cards",
        price=Decimal("999.00"),
        stock=5,
        description="Enthusiast 4K gaming GPU.",
        image_key="graphics-cards/gpu-gigabyte-rtx-5080.jpg",
        specs={"vram": "16GB GDDR7", "bus": "256-bit", "tdp": "360W", "ports": "3x DP 2.1b, 1x HDMI 2.1"},
    ),
    Product(
        id="gpu-gigabyte-rtx-5090",
        name="GeForce RTX 5090 GAMING OC 32G",
        brand="Gigabyte",
        category="graphics-cards",
        price=Decimal("1999.00"),
        stock=2,
        description="Flagship Blackwell GPU for 4K and beyond.",
        image_key="graphics-cards/gpu-gigabyte-rtx-5090.jpg",
        specs={"vram": "32GB GDDR7", "bus": "512-bit", "tdp": "575W", "ports": "3x DP 2.1b, 1x HDMI 2.1"},
    ),
    # --- Graphics Cards: Sapphire (AMD Radeon RDNA 4) ---
    Product(
        id="gpu-sapphire-rx-9060-xt",
        name="Sapphire PULSE Radeon RX 9060 XT 16G",
        brand="Sapphire",
        category="graphics-cards",
        price=Decimal("349.00"),
        stock=14,
        description="1080p / 1440p RDNA 4 GPU with 16GB.",
        image_key="graphics-cards/gpu-sapphire-rx-9060-xt.jpg",
        specs={"vram": "16GB GDDR6", "bus": "128-bit", "tdp": "160W", "ports": "3x DP 2.1, 1x HDMI 2.1"},
    ),
    Product(
        id="gpu-sapphire-rx-9070-xt",
        name="Sapphire NITRO+ Radeon RX 9070 XT 16G",
        brand="Sapphire",
        category="graphics-cards",
        price=Decimal("599.00"),
        stock=9,
        description="High-end 1440p / 4K RDNA 4 GPU with 16GB.",
        image_key="graphics-cards/gpu-sapphire-rx-9070-xt.jpg",
        specs={"vram": "16GB GDDR6", "bus": "256-bit", "tdp": "304W", "ports": "3x DP 2.1, 1x HDMI 2.1"},
    ),
    # --- Storage: Samsung NVMe SSDs ---
    Product(
        id="ssd-samsung-980pro-250gb",
        name="Samsung 980 PRO 250GB NVMe SSD",
        brand="Samsung",
        category="storage",
        price=Decimal("54.99"),
        stock=30,
        description="Entry PCIe 4.0 NVMe drive.",
        image_key="storage/ssd-samsung-980pro-250gb.jpg",
        specs={"capacity": "250GB", "interface": "PCIe 4.0 NVMe", "form_factor": "M.2 2280", "read": "6400 MB/s"},
    ),
    Product(
        id="ssd-samsung-980pro-500gb",
        name="Samsung 980 PRO 500GB NVMe SSD",
        brand="Samsung",
        category="storage",
        price=Decimal("79.99"),
        stock=25,
        description="PCIe 4.0 NVMe drive.",
        image_key="storage/ssd-samsung-980pro-500gb.jpg",
        specs={"capacity": "500GB", "interface": "PCIe 4.0 NVMe", "form_factor": "M.2 2280", "read": "6900 MB/s"},
    ),
    Product(
        id="ssd-samsung-990pro-1tb",
        name="Samsung 990 PRO 1TB NVMe SSD",
        brand="Samsung",
        category="storage",
        price=Decimal("109.99"),
        stock=20,
        description="High-performance PCIe 4.0 NVMe drive.",
        image_key="storage/ssd-samsung-990pro-1tb.jpg",
        specs={"capacity": "1TB", "interface": "PCIe 4.0 NVMe", "form_factor": "M.2 2280", "read": "7450 MB/s"},
    ),
    Product(
        id="ssd-samsung-990pro-2tb",
        name="Samsung 990 PRO 2TB NVMe SSD",
        brand="Samsung",
        category="storage",
        price=Decimal("169.99"),
        stock=15,
        description="High-performance PCIe 4.0 NVMe drive.",
        image_key="storage/ssd-samsung-990pro-2tb.jpg",
        specs={"capacity": "2TB", "interface": "PCIe 4.0 NVMe", "form_factor": "M.2 2280", "read": "7450 MB/s"},
    ),
    Product(
        id="psu-corsair-rm850e",
        name="RM850e 850W 80+ Gold",
        brand="Corsair",
        category="power-supplies",
        price=Decimal("129.99"),
        stock=18,
        description="Fully modular ATX power supply.",
        image_key="products/psu-corsair-rm850e/main.webp",
        specs={"wattage": "850W", "rating": "80+ Gold", "modular": "Full", "form_factor": "ATX"},
    ),
    Product(
        id="case-lian-li-216",
        name="Lancool 216",
        brand="Lian Li",
        category="cases",
        price=Decimal("109.99"),
        stock=0,
        description="Airflow ATX mid-tower.",
        image_key="products/case-lian-li-216/main.webp",
        specs={"form_factor": "Mid Tower", "supports": "ATX / mATX / ITX", "gpu_clearance": "392mm", "included_fans": "3"},
    ),
    Product(
        id="mon-odyssey-g7",
        name="Odyssey G7 32\"",
        brand="Samsung",
        category="monitors",
        price=Decimal("649.00"),
        stock=5,
        description="32-inch 1440p 240Hz curved gaming monitor.",
        image_key="products/mon-odyssey-g7/main.webp",
        specs={"size": "32\"", "resolution": "2560x1440", "refresh": "240Hz", "panel": "VA"},
    ),
    Product(
        id="kbd-mx-keys",
        name="MX Keys S",
        brand="Logitech",
        category="keyboards",
        price=Decimal("109.00"),
        stock=40,
        description="Wireless low-profile productivity keyboard.",
        image_key="products/kbd-mx-keys/main.webp",
        specs={"layout": "Full-size", "connectivity": "Bluetooth / Logi Bolt", "backlight": "Yes"},
    ),
    Product(
        id="mouse-mx-master-3s",
        name="MX Master 3S",
        brand="Logitech",
        category="mice",
        price=Decimal("99.99"),
        stock=35,
        description="Wireless productivity mouse.",
        image_key="products/mouse-mx-master-3s/main.webp",
        specs={"dpi": "8000", "connectivity": "Bluetooth / Logi Bolt", "buttons": "7"},
    ),
    Product(
        id="headset-arctis-nova-7",
        name="Arctis Nova 7 Wireless",
        brand="SteelSeries",
        category="headsets",
        price=Decimal("149.99"),
        stock=12,
        description="Wireless gaming headset.",
        image_key=None,
        specs={"connectivity": "2.4GHz Wireless / Bluetooth", "drivers": "40mm", "mic": "Retractable"},
    ),
]
